#!/usr/bin/env bash
# Module: agents/memory — see AGENTS.md (Protected files) and opencode.json permission.edit.

# agents/memory/scripts/audit.sh
# Runs the three schema invariants in agents/memory/scripts/invariants.cypher.
# Exits 0 if all three return zero (or only the dump returns data), exits
# 1 if any invariant returns > 0.
#
# Project-agnostic: reads the group_id via lib/project.sh.
#
# Usage:
#   audit.sh               # run from any cwd, finds project root automatically

set -uo pipefail

HERE="$(cd "$(dirname "$0")" && pwd)"
# shellcheck source=lib/project.sh
source "$HERE/lib/project.sh"

_find_root() {
  local d="${1:-$PWD}"
  while [ "$d" != "/" ]; do
    [ -d "$d/agents/memory" ] && [ -f "$d/agents/memory/runtime/config/config.yaml" ] && [ -f "$d/agents/memory/scripts/memory.sh" ] && { echo "$d"; return 0; }
    d="$(dirname "$d")"
  done
  return 1
}
ROOT="$(_find_root)"
cd "$ROOT/agents/memory/runtime"

# --- project (group_id) resolution ---
resolve_project || exit 2

CYPHER_FILE="$HERE/invariants.cypher"
[ -f "$CYPHER_FILE" ] || { echo "audit.sh: missing $CYPHER_FILE" >&2; exit 2; }

# --- Build the label list from the schema cache so adding a label to
# memory/config/config.yaml auto-flows into invariant 3. The cache is
# regenerated by schema.sh whenever config.yaml is newer.
SCHEMA_CACHE="$ROOT/runs/schema.cache"
if [ ! -f "$SCHEMA_CACHE" ]; then
  bash "$HERE/schema.sh" labels >/dev/null
fi
LABEL_LIST="$(cut -d'|' -f1 "$SCHEMA_CACHE" | awk '{printf "\x27%s\x27,", $0}' | sed 's/,$//')"
[ -n "$LABEL_LIST" ] || { echo "audit.sh: no schema labels found" >&2; exit 2; }

# Substitute __GROUP_ID__ and __SCHEMA_LABELS__. The fourth statement (the
# distribution dump) gets __GROUP_ID__ too; __SCHEMA_LABELS__ is irrelevant
# there but harmless to substitute.
SUBSTITUTED="$(awk -v gid="$GROUP_ID" -v list="$LABEL_LIST" '
  { gsub(/__GROUP_ID__/, gid); gsub(/__SCHEMA_LABELS__/, list); print }
' "$CYPHER_FILE")"

# Sanity: make sure both placeholders were actually substituted (catches
# the case where someone edits the cypher and adds a new __FOO__ marker).
if echo "$SUBSTITUTED" | grep -q '__[A-Z_]\+__'; then
  echo "audit.sh: WARNING — unresolved placeholder(s) in invariants.cypher:" >&2
  echo "$SUBSTITUTED" | grep -nE '__[A-Z_]+__' >&2
fi

# The cypher file has 4 statements split by ";" at end of line. neo4j-cli
# handles the splitting if we pass it as a single string. Each statement runs
# in its own transaction so a failure of one does not block the next.
out="$(neo4j-cli query "$SUBSTITUTED" --format toon)"
ec=$?

echo "$out"
echo

# --- parse results to determine pass/fail ---
# We expect three numeric counts (unlabeled, orphans, out_of_schema) and a
# final distribution dump. A label that is not in the schema is an automatic
# failure.
unlabeled="$(echo "$out" | grep -A1 '^rows' | grep -oE 'unlabeled[^,}]*' | head -1 || true)"
orphans="$(echo "$out"   | grep -A1 '^rows' | grep -oE 'orphans[^,}]*'   | head -1 || true)"
oos="$(echo "$out"       | grep -A1 '^rows' | grep -oE 'out_of_schema[^,}]*' | head -1 || true)"

# A safer parse: extract the values associated with the three keys using
# neo4j-cli's toon output. In toon, a row renders as `{key: value}` so we
# pull the numeric value of each.
_get() {
  local key="$1"
  echo "$out" | grep -oE "${key}:[[:space:]]*[0-9]+" | head -1 | grep -oE '[0-9]+' || echo 0
}

u="$(_get unlabeled)"
o="$(_get orphans)"
s="$(_get out_of_schema)"

echo "--- audit summary ---"
printf 'group_id     = %s\n' "$GROUP_ID"
printf 'unlabeled    = %s\n' "$u"
printf 'orphans      = %s\n' "$o"
printf 'out_of_schema= %s\n' "$s"

# A row labelled "out_of_schema" is only a failure if the count > 0 OR if
# a non-empty label was returned. We treat any non-zero value as a fail.
if [ "$u" != "0" ] || [ "$o" != "0" ] || [ "$s" != "0" ]; then
  echo "audit: FAIL"
  exit 1
fi

echo "audit: PASS"
exit 0
